import {spawn} from "node:child_process";
import {randomBytes, randomUUID} from "node:crypto";
import {createServer} from "node:net";
import path from "node:path";

import {expect, test} from "@playwright/test";
import Database from "better-sqlite3";

test("@live-zhipu-image encrypted Settings key generates and selects exactly one validated image", async ({page}, testInfo) => {
  test.setTimeout(900_000);
  const apiKey = readLegacyZhipuKey(); const port = await getFreePort(); const baseURL = `http://127.0.0.1:${port}`; const databasePath = testInfo.outputPath("live-zhipu-image.sqlite3"); const workerRoot = testInfo.outputPath("worker"); const storageRoot = testInfo.outputPath("assets"); const masterKey = randomBytes(32).toString("base64");
  const sharedEnv = {STORYVIDEOGEN_DATABASE_PATH: databasePath, STORYVIDEOGEN_MIGRATIONS_DIR: path.resolve("server", "migrations"), STORYVIDEOGEN_SECRET_MASTER_KEY: masterKey, STORYVIDEOGEN_SECRET_KEY_ID: "live-image-e2e-v1", STORYVIDEOGEN_WORKER_ROOT: workerRoot, STORYVIDEOGEN_STORAGE_ROOT: storageRoot, STORYVIDEOGEN_WORKER_FIXTURE_MODE: "0", STORYVIDEOGEN_ZHIPU_IMAGE_MODEL: process.env.STORYVIDEOGEN_ZHIPU_IMAGE_MODEL || "cogview-3-flash", STORYVIDEOGEN_WORKER_LEASE_SECONDS: "10", STORYVIDEOGEN_WORKER_TIMEOUT_SECONDS: "1200", STORYVIDEOGEN_WORKER_SILENCE_SECONDS: "720"};
  let server = startProcess(["server/dist/index.js"], {...sharedEnv, STORYVIDEOGEN_NODE_HOST: "127.0.0.1", STORYVIDEOGEN_NODE_PORT: String(port), STORYVIDEOGEN_NODE_LOG_LEVEL: "warn"}); let worker;
  try {
    await waitForReady(`${baseURL}/health/ready`, server);
    await page.goto(`${baseURL}/settings/providers`); await page.getByRole("button", {name: "Need an account? Register"}).click(); await page.getByLabel("Username").fill("live-zhipu-image-user"); await page.getByLabel("Password").fill("live-zhipu-image-password"); await page.getByRole("button", {name: "Create account"}).click();
    await page.getByLabel("Zhipu AI API key").fill(apiKey); await page.getByRole("button", {name: "Save", exact: true}).first().click(); await expect(page.getByText("Provider key saved securely.")).toBeVisible();
    await page.goto(`${baseURL}/create`); await page.getByLabel("Story name").fill("Live image check"); await page.getByLabel("Full story").fill("A solitary lighthouse stands above a moonlit sea."); await page.getByRole("button", {name: "Save draft"}).click(); await expect(page).toHaveURL(/\/create\?story=/);
    const storyId = new URL(page.url()).searchParams.get("story"); const seeded = seedPlannedScene(databasePath, storyId); await page.reload(); await expect(page.getByRole("heading", {name: "Review 1 scenes"})).toBeVisible();
    const queued = await page.evaluate(async ({sceneId, promptId}) => { const csrf = document.cookie.split("; ").find((entry) => entry.startsWith("storyvideogen_csrf="))?.split("=")[1]; const response = await fetch(`/api/v1/scenes/${sceneId}/actions/images`, {method: "POST", credentials: "same-origin", headers: {"content-type": "application/json", "idempotency-key": crypto.randomUUID(), "x-csrf-token": csrf || ""}, body: JSON.stringify({promptId, provider: "zhipu", count: 1})}); if (!response.ok) throw new Error(await response.text()); return response.json(); }, seeded);
    worker = startProcess(["server/dist/worker.js", "--once"], {...sharedEnv, STORYVIDEOGEN_NODE_LOG_LEVEL: "silent"});
    await expect.poll(async () => (await (await page.request.get(`${baseURL}/api/v1/jobs/${queued.job.id}`)).json()).job.state, {timeout: 720_000, intervals: [1000, 3000, 5000]}).toBe("succeeded"); expect(await waitForExit(worker, 20_000)).toBe(0);
    const jobPayload = await (await page.request.get(`${baseURL}/api/v1/jobs/${queued.job.id}`)).json(); expect(jobPayload.job.result).toMatchObject({provider: "zhipu", model: sharedEnv.STORYVIDEOGEN_ZHIPU_IMAGE_MODEL, readyCount: 1, failedCount: 0});
    await page.reload(); const candidateArea = page.getByLabel("Scene 1 image candidates"); await expect(candidateArea.locator("img")).toHaveCount(1); await candidateArea.getByRole("button", {name: "Choose image"}).click(); await expect(candidateArea.getByRole("button", {name: "Selected"})).toBeVisible();
    const candidates = await (await page.request.get(`${baseURL}/api/v1/stories/${storyId}/image-candidates`)).json(); expect(candidates.candidates).toHaveLength(1); expect(candidates.candidates[0]).toMatchObject({provider: "zhipu", model: sharedEnv.STORYVIDEOGEN_ZHIPU_IMAGE_MODEL, status: "ready", isSelected: true}); expect(candidates.candidates[0].asset.mimeType).toMatch(/^image\/(png|jpeg|gif)$/); expect(candidates.candidates[0].asset.byteSize).toBeGreaterThan(100);
    expect(`${server.output.join("")} ${worker.output.join("")} ${JSON.stringify(jobPayload)} ${JSON.stringify(candidates)}`).not.toContain(apiKey); expect(`${server.output.join("")} ${worker.output.join("")}`).not.toMatch(/authorization\s*:/i);
  } finally { await stopProcess(worker); await stopProcess(server); }
});

test("@live-zhipu-auto full SCP-173 automation produces an MP4", async ({page}, testInfo) => {
  test.setTimeout(1_800_000);
  const apiKey = readLegacyZhipuKey(); const port = await getFreePort(); const baseURL = `http://127.0.0.1:${port}`; const databasePath = testInfo.outputPath("live-zhipu-auto.sqlite3"); const workerRoot = testInfo.outputPath("worker-auto"); const storageRoot = testInfo.outputPath("assets-auto"); const masterKey = randomBytes(32).toString("base64");
  const sharedEnv = {STORYVIDEOGEN_DATABASE_PATH: databasePath, STORYVIDEOGEN_MIGRATIONS_DIR: path.resolve("server", "migrations"), STORYVIDEOGEN_SECRET_MASTER_KEY: masterKey, STORYVIDEOGEN_SECRET_KEY_ID: "live-auto-e2e-v1", STORYVIDEOGEN_WORKER_ROOT: workerRoot, STORYVIDEOGEN_STORAGE_ROOT: storageRoot, STORYVIDEOGEN_WORKER_FIXTURE_MODE: "0", STORYVIDEOGEN_ZHIPU_TEXT_MODEL: process.env.STORYVIDEOGEN_ZHIPU_TEXT_MODEL || "glm-5.2", STORYVIDEOGEN_ZHIPU_IMAGE_MODEL: process.env.STORYVIDEOGEN_ZHIPU_IMAGE_MODEL || "cogview-3-flash", STORYVIDEOGEN_WORKER_LEASE_SECONDS: "30", STORYVIDEOGEN_WORKER_TIMEOUT_SECONDS: "3600", STORYVIDEOGEN_WORKER_SILENCE_SECONDS: "720"};
  let server = startProcess(["server/dist/index.js"], {...sharedEnv, STORYVIDEOGEN_NODE_HOST: "127.0.0.1", STORYVIDEOGEN_NODE_PORT: String(port), STORYVIDEOGEN_NODE_LOG_LEVEL: "warn"}); let worker;
  try {
    await waitForReady(`${baseURL}/health/ready`, server);
    await page.goto(`${baseURL}/settings/providers`); await page.getByRole("button", {name: "Need an account? Register"}).click(); await page.getByLabel("Username").fill("live-zhipu-auto-user"); await page.getByLabel("Password").fill("live-zhipu-auto-password"); await page.getByRole("button", {name: "Create account"}).click();
    await page.getByLabel("Zhipu AI API key").fill(apiKey); await page.getByRole("button", {name: "Save", exact: true}).first().click(); await expect(page.getByText("Provider key saved securely.")).toBeVisible();
    await page.goto(`${baseURL}/create`); await page.getByLabel("Story name").fill("SCP-173 full automation"); await page.getByLabel("Full story").fill(scp173Story); await page.getByRole("button", {name: "Save draft"}).click(); await expect(page).toHaveURL(/\/create\?story=/); await page.getByLabel("Target scene length (seconds)").fill("60"); const storyId = new URL(page.url()).searchParams.get("story");
    worker = startProcess(["server/dist/worker.js"], {...sharedEnv, STORYVIDEOGEN_NODE_LOG_LEVEL: "silent"}); await page.getByRole("button", {name: "Auto-create podcast"}).click();
    const automation = await waitForAutomation(page, `${baseURL}/api/v1/stories/${storyId}/automation`, 1_500_000); expect(automation).toMatchObject({state: "completed", storyStatus: "completed"});
    await page.reload(); await expect(page.getByRole("link", {name: "Play finished video"})).toBeVisible(); const videoUrl = await page.getByRole("link", {name: "Play finished video"}).getAttribute("href"); const video = await page.request.get(`${baseURL}${videoUrl}`); expect(video.status()).toBe(200); expect(video.headers()["content-type"]).toMatch(/^video\/mp4/); expect((await video.body()).subarray(4, 8).toString("ascii")).toBe("ftyp");
    const database = new Database(databasePath, {readonly: true}); try { const sceneCount = database.prepare("SELECT COUNT(*) AS count FROM scenes WHERE story_id = ?").get(storyId).count; expect(sceneCount).toBeGreaterThan(0); expect(database.prepare("SELECT COUNT(*) AS count FROM jobs WHERE story_id = ? AND state = 'succeeded'").get(storyId).count).toBe(sceneCount + 2); expect(database.prepare("SELECT COUNT(*) AS count FROM image_candidates JOIN scenes ON scenes.id = image_candidates.scene_id WHERE scenes.story_id = ? AND image_candidates.is_selected = 1").get(storyId).count).toBe(sceneCount); } finally { database.close(); }
    expect(`${server.output.join("")} ${worker.output.join("")}`).not.toContain(apiKey);
  } finally { await stopProcess(worker); await stopProcess(server); }
});

const scp173Story = `Item #: SCP-173

Object Class: Euclid

Special Containment Procedures: Item SCP-173 is to be kept in a locked container at all times. When personnel must enter SCP-173's container, no fewer than 3 may enter at any time and the door is to be relocked behind them. At all times, two persons must maintain direct eye contact with SCP-173 until all personnel have vacated and relocked the container.

Description: Moved to Site-19 1993. Origin is as of yet unknown. It is constructed from concrete and rebar with traces of Krylon brand spray paint. SCP-173 is animate and extremely hostile. The object cannot move while within a direct line of sight. Line of sight must not be broken at any time with SCP-173. Personnel assigned to enter container are instructed to alert one another before blinking. Object is reported to attack by snapping the neck at the base of the skull, or by strangulation. In the event of an attack, personnel are to observe Class 4 hazardous object containment procedures.

Personnel report sounds of scraping stone originating from within the container when no one is present inside. This is considered normal, and any change in this behaviour should be reported to the acting HMCL supervisor on duty.

The reddish brown substance on the floor is a combination of feces and blood. Origin of these materials is unknown. The enclosure must be cleaned on a bi-weekly basis.`;

function seedPlannedScene(databasePath, storyId) { if (!storyId) throw new Error("Story ID is missing."); const database = new Database(databasePath); try { const story = database.prepare("SELECT source_text FROM stories WHERE id = ?").get(storyId); if (!story) throw new Error("Story was not persisted."); const sceneId = randomUUID(); const promptId = randomUUID(); const now = new Date().toISOString(); const transaction = database.transaction(() => { database.prepare("INSERT INTO scenes (id, story_id, position, source_start, source_end, source_text, narration_text, status, created_at, updated_at) VALUES (?, ?, 0, 0, ?, ?, ?, 'planned', ?, ?)").run(sceneId, storyId, story.source_text.length, story.source_text, "一座孤独的灯塔矗立在月光下的海面之上。", now, now); database.prepare("INSERT INTO image_prompts (id, scene_id, position, prompt_text, provider, model, status, created_at, updated_at) VALUES (?, ?, 0, ?, 'zhipu', 'test-seed', 'ready', ?, ?)").run(promptId, sceneId, "Cinematic wide shot of a solitary lighthouse above a moonlit sea, professional podcast illustration, no text", now, now); database.prepare("UPDATE stories SET status = 'planned', version = version + 1, updated_at = ? WHERE id = ?").run(now, storyId); }); transaction(); return {sceneId, promptId}; } finally { database.close(); } }
function readLegacyZhipuKey() { if (process.env.ZAI_API_KEY?.trim()) return process.env.ZAI_API_KEY.trim(); const database = new Database(path.resolve("output", "ui_auth.sqlite3"), {readonly: true, fileMustExist: true}); try { const row = database.prepare("SELECT value FROM user_api_keys WHERE name = 'ZAI_API_KEY' AND length(trim(value)) > 0 ORDER BY updated_at DESC LIMIT 1").get(); if (!row?.value) throw new Error("Set ZAI_API_KEY or save it in the legacy Settings database."); return String(row.value); } finally { database.close(); } }
async function waitForAutomation(page, url, timeout) { const deadline = Date.now() + timeout; while (Date.now() < deadline) { const result = await (await page.request.get(url)).json(); if (result.state === "completed") return result; if (result.state === "failed") throw new Error(`Automation failed: ${result.errorCode || "UNKNOWN"}: ${result.errorMessage || "No error details were returned."}`); await new Promise((resolve) => setTimeout(resolve, 2000)); } throw new Error(`Automation did not complete within ${Math.round(timeout / 1000)} seconds.`); }
function startProcess(args, environment) { const output = []; const child = spawn(process.execPath, args, {cwd: process.cwd(), env: {...process.env, ...environment}, windowsHide: true, stdio: ["ignore", "pipe", "pipe"]}); child.stdout.on("data", (chunk) => output.push(String(chunk))); child.stderr.on("data", (chunk) => output.push(String(chunk))); child.output = output; return child; }
async function waitForReady(url, child) { const deadline = Date.now() + 20_000; while (Date.now() < deadline) { if (child.exitCode !== null) throw new Error(`Server exited early: ${child.output.join("")}`); try { if ((await fetch(url)).status === 200) return; } catch {} await new Promise((resolve) => setTimeout(resolve, 100)); } throw new Error(`Server readiness timed out: ${child.output.join("")}`); }
function waitForExit(child, timeout) { if (child.exitCode !== null) return Promise.resolve(child.exitCode); return Promise.race([new Promise((resolve) => child.once("exit", resolve)), new Promise((_, reject) => setTimeout(() => reject(new Error(`Process timed out: ${child.output.join("")}`)), timeout))]); }
async function stopProcess(child) { if (!child || child.exitCode !== null) return; const exited = new Promise((resolve) => child.once("exit", resolve)); child.kill("SIGTERM"); await Promise.race([exited, new Promise((resolve) => setTimeout(resolve, 5000))]); if (child.exitCode === null) { child.kill("SIGKILL"); await exited; } }
function getFreePort() { return new Promise((resolve, reject) => { const server = createServer(); server.unref(); server.once("error", reject); server.listen(0, "127.0.0.1", () => { const address = server.address(); if (!address || typeof address === "string") { server.close(); reject(new Error("Unable to allocate a live-test port.")); return; } server.close((error) => error ? reject(error) : resolve(address.port)); }); }); }
