import {expect, test} from "@playwright/test";

import {startFixtureWorker} from "./helpers/worker-process.js";
const tinyPng = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=", "base64");

test("@m8 @m13 selected scenes render a downloadable 1080p podcast with external artifacts", async ({page}) => {
  test.setTimeout(120_000);
  expect((await page.request.post("/api/v1/auth/register", {data: {username: "m8-render", password: "render-password"}})).status()).toBe(201);
  await page.goto("/create"); await page.getByLabel("Story name").fill("Rendered lighthouse story"); await page.getByLabel("Full story").fill("A lighthouse keeper raises a lantern above the dark sea."); await page.getByRole("button", {name: "Save draft"}).click(); await page.getByRole("button", {name: "Plan full story"}).click(); expect(await startFixtureWorker()).toBe(0); await expect(page.getByRole("heading", {name: "Review 1 scenes"})).toBeVisible({timeout: 20_000}); await page.locator(".scene-card").first().getByRole("button", {name: "Split"}).click(); await expect(page.getByRole("heading", {name: "Review 2 scenes"})).toBeVisible();
  for (const [index, card] of (await page.locator(".scene-card").all()).entries()) { await card.getByLabel("Upload an image for this scene").setInputFiles({name: `scene-${index + 1}.png`, mimeType: "image/png", buffer: tinyPng}); await card.getByRole("button", {name: "Add candidate"}).click(); const candidates = page.getByLabel(`Scene ${index + 1} image candidates`); await expect(candidates.locator("img")).toHaveCount(1); await candidates.getByRole("button", {name: "Choose image"}).click(); }
  await page.getByLabel("Background music").setInputFiles({name: "ambient.wav", mimeType: "audio/wav", buffer: silentWav()}); await page.getByLabel("I have permission to use this music").check(); await page.getByLabel("Music volume").evaluate((element) => { const input = element; input.value = "0.10"; input.dispatchEvent(new Event("input", {bubbles: true})); }); await page.getByRole("button", {name: "Upload music"}).click(); await expect(page.getByRole("link", {name: "Download music"})).toBeVisible();
  await page.getByRole("button", {name: "Render podcast video"}).click(); const worker = startFixtureWorker(); await expect(page.getByRole("link", {name: "Play finished video"})).toBeVisible({timeout: 90_000}); expect(await worker).toBe(0); const storyId = new URL(page.url()).searchParams.get("story");
  const renderJob = await latestRenderJob(page, storyId); expect(renderJob.result.subtitlesBurnedIn).toBe(true);
  const videoUrl = await page.getByRole("link", {name: "Play finished video"}).getAttribute("href"); const video = await page.request.get(videoUrl); expect(video.status()).toBe(200); expect(video.headers()["content-type"]).toMatch(/^video\/mp4/); expect((await video.body()).subarray(4, 8).toString("ascii")).toBe("ftyp");
  const subtitleUrl = await page.getByRole("link", {name: "Download subtitle"}).getAttribute("href"); const subtitle = await page.request.get(subtitleUrl); const subtitleText = await subtitle.text(); expect(subtitleText).toMatch(/00:00:00,000 --> 00:00:03,000/); expect(subtitleText).toMatch(/2\r?\n00:00:03,000 --> 00:00:06,000/); await page.reload(); await expect(page.getByText("completed", {exact: false}).first()).toBeVisible(); await expect(page.getByRole("link", {name: "Play finished video"})).toBeVisible();
});

async function latestRenderJob(page, storyId) { const automation = await (await page.request.get(`/api/v1/stories/${storyId}/automation`)).json(); if (automation.currentJob?.type === "render_video") return (await (await page.request.get(`/api/v1/jobs/${automation.currentJob.id}`)).json()).job; const events = await (await page.request.get("/api/v1/events?after=0")).json(); const completed = [...events.events].reverse().find((event) => event.eventType === "completed" && event.payload?.subtitlesBurnedIn === true); if (!completed?.jobId) throw new Error("Render job was not found."); return (await (await page.request.get(`/api/v1/jobs/${completed.jobId}`)).json()).job; }

function silentWav() { const sampleRate = 8_000; const seconds = 1; const dataSize = sampleRate * seconds * 2; const buffer = Buffer.alloc(44 + dataSize); buffer.write("RIFF", 0); buffer.writeUInt32LE(36 + dataSize, 4); buffer.write("WAVEfmt ", 8); buffer.writeUInt32LE(16, 16); buffer.writeUInt16LE(1, 20); buffer.writeUInt16LE(1, 22); buffer.writeUInt32LE(sampleRate, 24); buffer.writeUInt32LE(sampleRate * 2, 28); buffer.writeUInt16LE(2, 32); buffer.writeUInt16LE(16, 34); buffer.write("data", 36); buffer.writeUInt32LE(dataSize, 40); return buffer; }
