import type {BillingRepository} from "./billingRepository.js";
import {ApiError} from "../http/errors.js";

export class BillingService {
  constructor(private readonly repository: BillingRepository, private readonly fakePayments: boolean) {}
  summary(userId: string) { const now = new Date().toISOString(); this.repository.ensureTrial(userId, now); const active = this.repository.active(userId, now); const usage = active ? this.repository.usage(userId, String(active.id)) : []; return {subscription: active ? {id: active.id, planCode: active.plan_code, displayName: active.display_name, periodStart: active.period_start, periodEnd: active.period_end, state: active.state, quotas: JSON.parse(String(active.quota_json)), usage: Object.fromEntries(usage.map((item) => [item.unitType, item.quantity]))} : null, plans: this.repository.plans().map((plan) => ({...plan, quotas: JSON.parse(plan.quotaJson), quotaJson: undefined})), orders: this.repository.orders(userId), paymentMode: this.fakePayments ? "fake" : "disabled"}; }
  createOrder(userId: string, planValue: unknown) { if (!this.fakePayments) throw new ApiError(503, "PAYMENTS_DISABLED", "Payments are not configured."); const plan = this.repository.plans().find((item) => item.code === planValue && item.priceFen > 0); if (!plan) throw new ApiError(400, "PLAN_INVALID", "Choose an available paid plan."); const now = new Date().toISOString(); const id = this.repository.createOrder(userId, plan.code, plan.priceFen, "pending", `weixin://wxpay/fake/${Date.now()}`, now); return this.repository.orders(userId).find((order: any) => order.id === id); }
  completeFake(userId: string, orderId: string, outcomeValue: unknown) { if (!this.fakePayments) throw new ApiError(404, "NOT_FOUND", "The payment test action is unavailable."); const outcome = outcomeValue === "paid" ? "paid" : outcomeValue === "failed" ? "failed" : undefined; if (!outcome) throw new ApiError(400, "PAYMENT_OUTCOME_INVALID", "Choose paid or failed."); if (!this.repository.updateFakeOrder(userId, orderId, outcome, new Date().toISOString())) throw new ApiError(409, "PAYMENT_STATE_INVALID", "The order cannot be updated."); return this.summary(userId); }
  assertEntitled(userId: string, unitType: string, quantity = 1): void { const summary = this.summary(userId); if (!summary.subscription) throw new ApiError(402, "SUBSCRIPTION_REQUIRED", "An active plan is required to start generation."); const quota = Number(summary.subscription.quotas[unitType] ?? 0); const used = Number(summary.subscription.usage[unitType] ?? 0); if (!Number.isSafeInteger(quantity) || quantity < 1 || used + quantity > quota) throw new ApiError(402, "QUOTA_EXCEEDED", `Your ${unitType.replaceAll("_", " ")} quota is exhausted.`); }
  record(userId: string, unitType: string, quantity: number, storyId: string | null, jobId: string): void { const active = this.repository.active(userId, new Date().toISOString()); if (active) this.repository.addUsage(userId, String(active.id), unitType, quantity, storyId, jobId); }
}
